### ISSUE TITLE
can you use this for pull requests?

### ISSUE THREAD

**Issue by cjw296** [andreif/stasher#1]
So, I got here from https://github.com/travis-ci/travis-ci/issues/7392.

I've been on a similar sad trail with Travis for a while:
https://travis-ci.community/t/how-can-i-share-coverage-information-between-build-stages-in-prs-from-forks/859/20

`stasher` looks great, but have you got it to work on pull requests from repos other than your own? My understanding is that, in this case, your Travis secrets will not be present in the build so stasher won't have the creds to post the coverage information. Is that the case or have you found a way around that?

**Comment by andreif** [comment]
Yeah, you would have to skip testing such PRs if I recall correctly and test after merge, probably develop branch first etc. Also, have a look on CircleCI - I made some runs there and this particular problem is solved nicely there.

**Comment by andreif** [comment]
Btw, there is an issue with rerunning failed builds with stasher. A job can randomly fail and your build will get stuck on coverage. I don't use it anymore so it was left unfixed.

**Comment by cjw296** [comment]
Okay, thanks!
